server {
    location / {
        add_header Cache-Control "public, max-age=0, must-revalidate";

        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /tonconnect-manifest.json {
        default_type application/json;
        return 200 "{\"url\":\"https://$host\",\"name\":\"ION Minter\",\"iconUrl\":\"https://$host/logo192.png\"}";
    }

    # Handle 404 errors
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Handle server errors (50x)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
